### ISSUE TITLE
Validate the use of division operator in this package for MakeCode update

### ISSUE THREAD

**Issue by abchatra** [jdarling/pxt-pca9685#1]
MakeCode for the micro:bit update is coming soon. Part of the update is floating point support. Existing MakeCode website supports only integer division which means
1/2 = 0
With this update 1/2 = 0.5

__Action for you:__
We have automatically detected this package uses division operator. Please take one of the following actions
- If the change to floating point division doesn't matter you can ignore and close this issue.
- If you want integer division then update your package typescript code to use integer division. Change  _a/b_ to  _Math.idiv(a, b)_

You can test your package on the update here: https://makecode.microbit.org/beta

All the details on the update: https://makecode.com/blog/microbit/v1-beta

div found in driver.ts

**Comment by jdarling** [comment]
Sorry I've been away from a connection for a while now.  Looks like updates are as follows:

Line 224 - setOffsetsFromFreq
Line 270 - calcFreqPrescaler
Line 305 - calcFreqOffset
Line 412 - setCRServoPosition
Line 438 - setServoLimits

I'll create a branch, fix and PR this hopefully by end of week.  Cool that you guys are notifying authors of breaking changes like this one.

**Comment by jdarling** [comment]
Fixed in branch idiv-update, PR #2 

Monkey patches Math.idiv and retains integer math so v0 will continue to work.

@abchatra in the future it would be nice if there were a way to test changes from branches so that we didn't have to push breaking changes to test.

Will the package still be available in both versions?

**Comment by abchatra** [comment]
We have already added Math.idiv to v0, so you don't need to check for its presence (but doesn't hurt to do it either).

You can always load the exact version using GitHub URL in the package search.

Package will be available in both versions.

**Comment by jdarling** [comment]
@abchatra must have missed that someplace in the docs.  Admittedly I did a quick scan of the blog post, and a quick and dirty search with manual replace in the source but didn't want to break my students code so made sure to monkey patch ;) .
