### ISSUE TITLE
create a release

### ISSUE THREAD

**Issue by pelikhan** [jdarling/pxt-pca9685#9]
You need to create a release in this repository. Follow the instructions at https://makecode.com/extensions/versioning.

**Comment by alankrantas** [comment]
There is a [release](https://github.com/jdarling/pxt-pca9685/releases/tag/v0.04), although the version didn't show up in MakeCode.

```
{
    "name": "pca9685",
    "version": "0.0.4",
...
}
```

Will it work if I change the name above to "pxt-pca9685" and make a new release?

EDIT: made a fork and tried it. Seems to work. I'll go ahead and merge my PR.

EDIT: PR merged and looks good in MakeCode from my side.

**Comment by pelikhan** [comment]
Great looks like the new release got picked up!

________________________________

**Comment by pelikhan** [comment]
Great thanks for doing the new release!
